spring:
  application:
    name: order-service
  config:
    import: 'optional:configserver:${config-server:http://192.168.1.15:9090/}'
  profiles:
    active: dev
  cloud:
    config:
      uri: '${config-server:http://192.168.1.15:9090/}'
      name: app-server,order-service
  redis:
  host: 192.168.1.17
  port: 6379